[phases.setup]
nixPkgs = ["python311", "git"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 1800 --graceful-timeout 120 --keep-alive 10"
